language: objective-c
osx_image: xcode8.2
before_install:
  - gem install cocoapods   # Travis is not always on latest version
  - gem install xcpretty
  - pod repo update > /dev/null
script:
  - ./TestApp/ci-build.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - eliza.sapir@kaltura.com
    on_success: change
    on_failure: always
